import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BossPanelLayoutClient } from "@/features/layouts/BossPanelLayoutClient";

/** Iran Sans Web (FaNum) — Medium = CSS weight 500 */
const iranSans500 = localFont({
  src: "../public/fonts/woff2/IRANSansWebFaNum_Medium.woff2",
  weight: "500",
  style: "normal",
  variable: "--font-iransans-500",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${iranSans500.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <BossPanelLayoutClient>{children}</BossPanelLayoutClient>
      </body>
    </html>
  );
}
